pipeline {
    agent any

    environment {
        IMAGE_NAME = "ooredoo-website-frontend"
        CONFIG_FOLDER = "environments/development/million"
        DOCKER_FILENAME = "Dockerfile"
        DOCKER_COMPOSE_FILENAME = "docker-compose.yml"
        IMAGE_NAME_COMPOSE = "${env.IMAGE_NAME}:${env.BUILD_ID}"
    }

    tools {
        jdk 'java'
        maven 'mvn'
    }

    stages {
        stage('build tools version ') { // for display purposes.
            steps {
                dir(WORKSPACE) {
                    sh 'mvn --version'
                    sh 'java -version'
                    sh 'docker --version'
                }
            }
        }

        stage('Build Docker image') {
            steps {
                script {
                    sh "docker build -t ${IMAGE_NAME}:${BUILD_ID} -f ${CONFIG_FOLDER}/${DOCKER_FILENAME} ."
                    sh "docker tag ${IMAGE_NAME}:${BUILD_ID} 172.16.97.41:5000/${IMAGE_NAME}:${BUILD_ID}"
                    sh "docker push 172.16.97.41:5000/${IMAGE_NAME}:${BUILD_ID}"
                }
            }
        }

        stage('Deploy using Docker Compose on 172.16.97.41') {
            steps {
            	sh "echo 'Start deployment on 172.16.97.41 for ${IMAGE_NAME}'"
            	sh "docker rm -f ${IMAGE_NAME} || true"
                sh "docker compose -f ${CONFIG_FOLDER}/${DOCKER_COMPOSE_FILENAME} up -d"
            }
        }
    }

    post {
        success {
            sh "echo 'success'"
        }
    }
}
